### ISSUE TITLE
php实现的直播状态API

### ISSUE THREAD

**Issue by lwd-temp** [Asoul-fan/Ikia#3]
源码：https://github.com/lwd-temp/site-api/blob/main/api/ikialive.php
API演示地址：https://api.lwd-temp.top/api/ikialive.php

返回值：-1，没开通直播间/0，没直播/1，有直播/2，无法处理

**Comment by Asoul-fan** [comment]
好好好

在 2022-06-01 22:36:29，Sunset ***@***.***> 写道：


源码：https://github.com/lwd-temp/site-api/blob/main/api/ikialive.php
API演示地址：https://api.lwd-temp.top/api/ikialive.php

返回值：-1，没开通直播间/0，没直播/1，有直播/2，无法处理

**Comment by Asoul-fan** [comment]
用nginx反向代理已实现
